import type { Metadata } from "next";
import { Noto_Sans} from "next/font/google";
import "./globals.css";

const geistMono = Noto_Sans({
  variable: "--font-geist-mono",
  weight: ["400","700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fun with Flags",
  description: "Generated by study",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
